name: Run tests
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        java-version: 18

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build with Maven
      run: mvn clean package

    - name: Run tests
      run: mvn test
