name: Testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -f HACLaditec/pom.xml clean test
      - name: Generate Jacoco Coverage Report
        run: mvn -f HACLaditec/pom.xml jacoco:report
      - name: Generate Allure Report
        run: mvn -f HACLaditec/pom.xml allure:report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: HACLaditec/target/site/allure-maven-plugin



      


