name: Testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
      - name: Install Allure Command Line
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.13.8/allure-2.13.8.zip
          unzip allure-2.13.8.zip -d allure
          sudo mv allure /usr/local
          sudo ln -s /usr/local/allure/bin/allure /usr/bin/allure
      - name: Build and Run Tests
        run: mvn -f HACLaditec/pom.xml test
      - name: Generate Allure Report
        run: allure generate --clean && allure open
        working-directory: HACLaditec/target/surefire-reports




      


